import type { JsonSchema, PluginToolDeclaration } from "@paperclipai/plugin-sdk";
import {
  ACTION_KEYS,
  FAMILY_LOGISTICS_TYPES,
  GIFT_STATUSES,
  INTERACTION_TYPES,
  RELATIONSHIP_CATEGORIES,
  RELATIONSHIP_TIERS,
  SCORE_VALUES,
} from "./constants.js";

export interface ActionToolDefinition extends PluginToolDeclaration {
  actionKey: string;
}

const stringSchema = (description: string, extras: JsonSchema = {}): JsonSchema => ({ type: "string", description, ...extras });
const numberSchema = (description: string, extras: JsonSchema = {}): JsonSchema => ({ type: "number", description, ...extras });
const booleanSchema = (description: string): JsonSchema => ({ type: "boolean", description });
const stringArraySchema = (description: string): JsonSchema => ({ type: "array", description, items: { type: "string" } });
const numberArraySchema = (description: string): JsonSchema => ({ type: "array", description, items: { type: "number" } });
const enumSchema = (values: readonly (string | number)[], description: string): JsonSchema => ({
  type: typeof values[0] === "number" ? "number" : "string",
  enum: [...values],
  description,
});
const objectSchema = (properties: Record<string, JsonSchema>, required: string[] = []): JsonSchema => ({
  type: "object",
  additionalProperties: false,
  properties,
  ...(required.length ? { required } : {}),
});

export const ACTION_TOOL_DEFINITIONS: ActionToolDefinition[] = [
  {
    actionKey: ACTION_KEYS.ADD_CONTACT,
    name: "add-contact",
    displayName: "Add contact",
    description: "Create a new relationship contact with optional birthday, notes, tags, and reconnect cadence.",
    parametersSchema: objectSchema({
      name: stringSchema("Contact name"),
      relationship: enumSchema(RELATIONSHIP_TIERS, "Relationship tier"),
      category: enumSchema(RELATIONSHIP_CATEGORIES, "Relationship category"),
      birthday: stringSchema("Birthday in MM-DD format"),
      anniversary: stringSchema("Anniversary or other important recurring date"),
      phone: stringSchema("Phone number"),
      email: stringSchema("Email address"),
      handle: stringSchema("Messaging or social handle"),
      notes: stringSchema("Free-form notes"),
      tags: stringArraySchema("Contact tags"),
      reminderFrequencyDays: numberSchema("Target lag threshold before reconnect nudges", { minimum: 1 }),
    }, ["name"]),
  },
  {
    actionKey: ACTION_KEYS.GET_CONTACTS,
    name: "get-contacts",
    displayName: "Get contacts",
    description: "List contacts, optionally filtered by tier, category, tag, or search query.",
    parametersSchema: objectSchema({
      tier: enumSchema(RELATIONSHIP_TIERS, "Only return contacts in this tier"),
      category: enumSchema(RELATIONSHIP_CATEGORIES, "Only return contacts in this category"),
      tag: stringSchema("Only return contacts containing this tag"),
      query: stringSchema("Case-insensitive search term matched against name, notes, and tags"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_CONTACT,
    name: "update-contact",
    displayName: "Update contact",
    description: "Update an existing contact and keep birthday/reminder state aligned.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      name: stringSchema("Updated contact name"),
      relationship: enumSchema(RELATIONSHIP_TIERS, "Updated relationship tier"),
      category: enumSchema(RELATIONSHIP_CATEGORIES, "Updated relationship category"),
      birthday: stringSchema("Birthday in MM-DD format; pass empty string to clear"),
      anniversary: stringSchema("Anniversary or recurring date"),
      phone: stringSchema("Phone number"),
      email: stringSchema("Email address"),
      handle: stringSchema("Messaging or social handle"),
      notes: stringSchema("Free-form notes"),
      tags: stringArraySchema("Tags"),
      reminderFrequencyDays: numberSchema("Updated reconnect threshold", { minimum: 1 }),
      lastContactedAt: stringSchema("ISO timestamp for the last contact"),
    }, ["contactId"]),
  },
  {
    actionKey: ACTION_KEYS.LOG_INTERACTION,
    name: "log-interaction",
    displayName: "Log interaction",
    description: "Record a call, message, meeting, gift, or other interaction with a contact and reconcile reconnect state.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      type: enumSchema(INTERACTION_TYPES, "Interaction type"),
      occurredAt: stringSchema("ISO timestamp for when the interaction happened"),
      durationMinutes: numberSchema("Optional interaction duration", { minimum: 0 }),
      summary: stringSchema("Short interaction summary"),
      topics: stringArraySchema("Topics discussed"),
      giftGiven: stringSchema("Gift given during the interaction"),
      location: stringSchema("Where the interaction happened"),
      notes: stringSchema("Detailed notes"),
      followUpItems: stringArraySchema("Follow-up tasks from the interaction"),
      quality: enumSchema(SCORE_VALUES, "Meaningfulness rating from 1 to 5"),
    }, ["contactId"]),
  },
  {
    actionKey: ACTION_KEYS.GET_INTERACTIONS,
    name: "get-interactions",
    displayName: "Get interactions",
    description: "List logged interactions, optionally limited to a single contact.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_INTERACTION,
    name: "update-interaction",
    displayName: "Update interaction",
    description: "Update an existing interaction record and refresh contact summary pointers.",
    parametersSchema: objectSchema({
      interactionId: stringSchema("Interaction id"),
      type: enumSchema(INTERACTION_TYPES, "Interaction type"),
      occurredAt: stringSchema("ISO timestamp"),
      durationMinutes: numberSchema("Duration in minutes", { minimum: 0 }),
      summary: stringSchema("Summary"),
      topics: stringArraySchema("Topics"),
      giftGiven: stringSchema("Gift given"),
      location: stringSchema("Location"),
      notes: stringSchema("Notes"),
      followUpItems: stringArraySchema("Follow-up tasks"),
      quality: enumSchema(SCORE_VALUES, "Meaningfulness rating"),
    }, ["interactionId"]),
  },
  {
    actionKey: ACTION_KEYS.UPSERT_BIRTHDAY_REMINDER,
    name: "upsert-birthday-reminder",
    displayName: "Upsert birthday reminder",
    description: "Create or update birthday reminder settings for a contact and sync the contact birthday field.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      date: stringSchema("Birthday in MM-DD format"),
      reminderDaysBefore: numberArraySchema("How many days before the birthday to nudge"),
      sent: booleanSchema("Whether the reminder has already been sent this cycle"),
      lastSentYear: numberSchema("Last year in which the reminder was sent"),
    }, ["contactId", "date"]),
  },
  {
    actionKey: ACTION_KEYS.GET_BIRTHDAYS,
    name: "get-birthdays",
    displayName: "Get birthdays",
    description: "List upcoming birthdays within a configurable lookahead window.",
    parametersSchema: objectSchema({
      days: numberSchema("Look ahead this many days", { minimum: 0 }),
    }),
  },
  {
    actionKey: ACTION_KEYS.ADD_GIFT_IDEA,
    name: "add-gift-idea",
    displayName: "Add gift idea",
    description: "Store a gift idea for a contact.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      description: stringSchema("Gift idea description"),
      occasion: stringSchema("Occasion, such as birthday or anniversary"),
      priceRange: stringSchema("Budget range"),
      links: stringArraySchema("Reference links"),
      notes: stringSchema("Notes"),
      status: enumSchema(GIFT_STATUSES, "Current gift status"),
    }, ["contactId", "description"]),
  },
  {
    actionKey: ACTION_KEYS.GET_GIFT_IDEAS,
    name: "get-gift-ideas",
    displayName: "Get gift ideas",
    description: "List gift ideas, optionally filtered to a specific contact or status.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      status: enumSchema(GIFT_STATUSES, "Gift status"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_GIFT_IDEA,
    name: "update-gift-idea",
    displayName: "Update gift idea",
    description: "Update gift idea details and lifecycle status.",
    parametersSchema: objectSchema({
      giftIdeaId: stringSchema("Gift idea id"),
      description: stringSchema("Gift idea description"),
      occasion: stringSchema("Occasion"),
      priceRange: stringSchema("Budget range"),
      links: stringArraySchema("Reference links"),
      notes: stringSchema("Notes"),
      status: enumSchema(GIFT_STATUSES, "Gift status"),
    }, ["giftIdeaId"]),
  },
  {
    actionKey: ACTION_KEYS.PLAN_SOCIAL_EVENT,
    name: "plan-social-event",
    displayName: "Plan social event",
    description: "Create a social event with attendees, timing, and reminders.",
    parametersSchema: objectSchema({
      title: stringSchema("Event title"),
      date: stringSchema("ISO date or timestamp"),
      time: stringSchema("Optional time hint"),
      location: stringSchema("Location"),
      attendees: stringArraySchema("Attendee contact ids"),
      organizerId: stringSchema("Organizer contact id"),
      description: stringSchema("Description"),
      reminderDaysBefore: numberArraySchema("Reminder lead times"),
      notes: stringSchema("Notes"),
    }, ["title", "date"]),
  },
  {
    actionKey: ACTION_KEYS.GET_SOCIAL_CALENDAR,
    name: "get-social-calendar",
    displayName: "Get social calendar",
    description: "List planned social events, optionally limited to the next N days or a specific attendee.",
    parametersSchema: objectSchema({
      days: numberSchema("Look ahead this many days", { minimum: 0 }),
      attendeeId: stringSchema("Only include events attended by this contact"),
      includePast: booleanSchema("Include events that have already happened"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_SOCIAL_EVENT,
    name: "update-social-event",
    displayName: "Update social event",
    description: "Update a planned social event.",
    parametersSchema: objectSchema({
      eventId: stringSchema("Event id"),
      title: stringSchema("Event title"),
      date: stringSchema("ISO date or timestamp"),
      time: stringSchema("Time hint"),
      location: stringSchema("Location"),
      attendees: stringArraySchema("Attendee contact ids"),
      organizerId: stringSchema("Organizer contact id"),
      description: stringSchema("Description"),
      reminderDaysBefore: numberArraySchema("Reminder lead times"),
      notes: stringSchema("Notes"),
    }, ["eventId"]),
  },
  {
    actionKey: ACTION_KEYS.ADD_CONVERSATION_NOTE,
    name: "add-conversation-note",
    displayName: "Add conversation note",
    description: "Capture a note about a contact or interaction.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      interactionId: stringSchema("Related interaction id"),
      content: stringSchema("Note content"),
      tags: stringArraySchema("Tags"),
    }, ["contactId", "content"]),
  },
  {
    actionKey: ACTION_KEYS.GET_CONVERSATION_NOTES,
    name: "get-conversation-notes",
    displayName: "Get conversation notes",
    description: "List conversation notes, optionally filtered by contact or tag.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      tag: stringSchema("Only include notes containing this tag"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_CONVERSATION_NOTE,
    name: "update-conversation-note",
    displayName: "Update conversation note",
    description: "Update an existing conversation note.",
    parametersSchema: objectSchema({
      noteId: stringSchema("Note id"),
      interactionId: stringSchema("Interaction id"),
      content: stringSchema("Note content"),
      tags: stringArraySchema("Tags"),
    }, ["noteId"]),
  },
  {
    actionKey: ACTION_KEYS.ADD_TO_RECONNECT_LIST,
    name: "add-to-reconnect-list",
    displayName: "Add reconnect item",
    description: "Manually add someone to the reconnect list.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
      reason: stringSchema("Why this person should be reconnected with"),
      suggestedOutreach: stringSchema("Suggested outreach angle"),
    }, ["contactId", "reason"]),
  },
  {
    actionKey: ACTION_KEYS.GET_RECONNECT_LIST,
    name: "get-reconnect-list",
    displayName: "Get reconnect list",
    description: "List reconnect candidates and attempt history.",
    parametersSchema: objectSchema({
      includeCompleted: booleanSchema("Include completed items as well"),
      contactId: stringSchema("Only include reconnect items for this contact"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_RECONNECT_ITEM,
    name: "update-reconnect-item",
    displayName: "Update reconnect item",
    description: "Update reconnect attempt counts, completion status, or outreach guidance.",
    parametersSchema: objectSchema({
      reconnectItemId: stringSchema("Reconnect item id"),
      reason: stringSchema("Reconnect reason"),
      suggestedOutreach: stringSchema("Suggested outreach text"),
      incrementAttempts: booleanSchema("Increment the attempt count by one"),
      lastAttemptedAt: stringSchema("ISO timestamp of last outreach attempt"),
      completed: booleanSchema("Mark the reconnect task complete or incomplete"),
      completedAt: stringSchema("ISO timestamp when completed"),
    }, ["reconnectItemId"]),
  },
  {
    actionKey: ACTION_KEYS.REFRESH_RECONNECT_LIST,
    name: "refresh-reconnect-list",
    displayName: "Refresh reconnect list",
    description: "Recompute stale contacts, create missing automatic reconnect items, and resolve outdated ones.",
    parametersSchema: objectSchema({
      defaultLagDays: numberSchema("Fallback lag threshold when a contact does not define one", { minimum: 1 }),
    }),
  },
  {
    actionKey: ACTION_KEYS.LOG_FAMILY_LOGISTICS,
    name: "log-family-logistics",
    displayName: "Log family logistics item",
    description: "Track a family coordination task such as transport, scheduling, healthcare, or finances.",
    parametersSchema: objectSchema({
      title: stringSchema("Task title"),
      type: enumSchema(FAMILY_LOGISTICS_TYPES, "Family logistics type"),
      responsibleContactId: stringSchema("Responsible contact id"),
      dueDate: stringSchema("ISO due date"),
      completed: booleanSchema("Whether the task is already completed"),
      notes: stringSchema("Notes"),
    }, ["title"]),
  },
  {
    actionKey: ACTION_KEYS.GET_FAMILY_LOGISTICS,
    name: "get-family-logistics",
    displayName: "Get family logistics",
    description: "List family logistics items, optionally filtered by status or owner.",
    parametersSchema: objectSchema({
      status: enumSchema(["pending", "completed"], "Task status filter"),
      responsibleContactId: stringSchema("Responsible contact id"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_FAMILY_LOGISTICS,
    name: "update-family-logistics",
    displayName: "Update family logistics",
    description: "Update a family logistics item.",
    parametersSchema: objectSchema({
      familyLogisticsId: stringSchema("Family logistics item id"),
      title: stringSchema("Task title"),
      type: enumSchema(FAMILY_LOGISTICS_TYPES, "Family logistics type"),
      responsibleContactId: stringSchema("Responsible contact id"),
      dueDate: stringSchema("ISO due date"),
      completed: booleanSchema("Completion state"),
      completedAt: stringSchema("ISO completed timestamp"),
      notes: stringSchema("Notes"),
    }, ["familyLogisticsId"]),
  },
  {
    actionKey: ACTION_KEYS.ADD_ELDERCARE_CHECKIN,
    name: "add-eldercare-checkin",
    displayName: "Add eldercare check-in",
    description: "Log an eldercare wellbeing check-in.",
    parametersSchema: objectSchema({
      elderContactId: stringSchema("Elder contact id"),
      checkinAt: stringSchema("ISO timestamp"),
      wellbeingScore: enumSchema(SCORE_VALUES, "Wellbeing score from 1 to 5"),
      mobilityScore: enumSchema(SCORE_VALUES, "Mobility score from 1 to 5"),
      moodScore: enumSchema(SCORE_VALUES, "Mood score from 1 to 5"),
      concerns: stringArraySchema("Open concerns"),
      followUpActions: stringArraySchema("Follow-up actions"),
      notes: stringSchema("Notes"),
    }, ["elderContactId"]),
  },
  {
    actionKey: ACTION_KEYS.GET_ELDERCARE_CHECKINS,
    name: "get-eldercare-checkins",
    displayName: "Get eldercare check-ins",
    description: "List eldercare check-ins, optionally filtered to one contact.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Elder contact id"),
    }),
  },
  {
    actionKey: ACTION_KEYS.UPDATE_ELDERCARE_CHECKIN,
    name: "update-eldercare-checkin",
    displayName: "Update eldercare check-in",
    description: "Update an eldercare check-in record.",
    parametersSchema: objectSchema({
      eldercareCheckinId: stringSchema("Eldercare check-in id"),
      checkinAt: stringSchema("ISO timestamp"),
      wellbeingScore: enumSchema(SCORE_VALUES, "Wellbeing score"),
      mobilityScore: enumSchema(SCORE_VALUES, "Mobility score"),
      moodScore: enumSchema(SCORE_VALUES, "Mood score"),
      concerns: stringArraySchema("Concerns"),
      followUpActions: stringArraySchema("Follow-up actions"),
      notes: stringSchema("Notes"),
    }, ["eldercareCheckinId"]),
  },
  {
    actionKey: ACTION_KEYS.GET_RELATIONSHIP_SUMMARY,
    name: "get-relationship-summary",
    displayName: "Get relationship summary",
    description: "Return a full cross-feature snapshot for a single contact.",
    parametersSchema: objectSchema({
      contactId: stringSchema("Contact id"),
    }, ["contactId"]),
  },
];
